Services
hiqdev/heppy pull request #38
Opened 2021-04-01 07:32 UTC by bladeroot

2021-04-01 08:00 UTC, hiqsol requested changes

2021-04-01 08:00 UTC, hiqsol commented on etc/systemd/heppy-rabbitmq-route.service
> +[Unit]
этот файл уноси отсюда в проект
он специфичный для проекта
и я думаю его надо объединить с запуском туннеля - это цельная задача

2021-04-01 08:30 UTC, bladeroot commented on etc/systemd/heppy-rabbitmq-route.service
> +[Unit]
Не совсем. Туннель - одно, а маршрутизация между портами - уже другое

2021-04-01 09:01 UTC, hiqsol commented on etc/systemd/heppy-rabbitmq-route.service
> +[Unit]
ну сделай 2 сервиса, но оба в проекте

2021-04-02 06:52 UTC, hiqsol approved these changes

2021-04-02 06:53 UTC, merged